name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    env:
      is_release: ${{ github.event_name == 'release' && github.event.action == 'created' }}
    steps:
      - uses: actions/checkout@v2
      # TODO reuse image
      - name: Install dependencies
        run: |
          yum groupinstall -y "Development Tools"
          yum install -y git autoconf automake libtool mingw32-gnutls mingw32-libxml2 mingw32-gtk3
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          bash autogen.sh
          mingw32-configure
          make winpkg
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: stoken-win32
          path: stoken-win32.zip
      - name: Rename release artifact
        if: env.is_release
        run: |
          mv stoken-win32.zip stoken-${{ github.event.release.tag_name }}-win32.zip
      - name: GH Release
        if: env.is_release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: stoken-v*-win32.zip
